# http://www.appveyor.com/docs/appveyor-yml

clone_depth: 10

environment:
  matrix:
    - nodejs_version: 10
    - nodejs_version: 12
    - nodejs_version: 14

platform:
  - x64

matrix:
  fast_finish: false

version: "{build}"
build: off
deploy: off

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm -g install npm
  - npm ci

test_script:
  - npm test

cache:
  # global npm cache
  - "%APPDATA%\\npm-cache"
